### ISSUE TITLE
updating the object wih new solutions (`add`, `add_list`)

### ISSUE THREAD

**Issue by naceee** [MilaNedic/moarchiving#3]

**Comment by naceee** [comment]
I didn't find any code (even in the original c code) for adding a new point to the archive, but this is written in the paper. Hopefully I can make it work, but if anyone finds some code, thats even better.
![slika](https://github.com/user-attachments/assets/b0cb6079-8830-4edc-afea-d4d8249a4324)

**Comment by MilaNedic** [comment]
I haven't found the code for this in the original C code for `hv_plus.c` but it may be available in the `hvc.c` file. Will let you know if I find anything useful.

**Comment by naceee** [comment]
There are some functions: `addPoint`, `addDomPoint` and `addNDPoint` in the `hvc.c` file, but not at all commented, so I'm having a hard time understanding anything from there. Am I right that `hvc.c` is the old implementaion and `hv_plus.c` is the improved one, or what is the difference between the two?

**Comment by naceee** [comment]
I managed to implement the `add` and `add_list` functions, following the instructions in the paper. I implemented it in a way that after adding points the hypervolume is calculated with the hypervolume computation algorithm. In the paper it says that it can be also done by adding the contribution of each added point (something like this is also used in the 2D case). Any idea which approach is better (maybe this is also a question for @ttusar)? 

![slika](https://github.com/user-attachments/assets/64147af4-2625-4798-a27e-0ec54243f38e)

**Comment by ttusar** [comment]
I would say the one that is quicker, but sadly don't know enough about details to be of help here.

**Comment by naceee** [comment]
Adding points one by one is about two times slower, than adding them all together. This is a graph showing the comparison, when adding only nondominated points  (from spherical distribution) - so the archive is getting bigger and bigger all the time, which is probably not the case. Any idea how to samlpe the points to get a more representative results? Maybe I can add some small ammount of noise to the points sampled from the spherical distribution?

![slika](https://github.com/user-attachments/assets/a0c0add7-0b74-4a75-a6cc-635fea4f7df5)

**Comment by naceee** [comment]
I get such results, when adding some noise ot the set of nondominated points, so the archive is not as big. 
![slika](https://github.com/user-attachments/assets/ad759d61-8905-44e3-a50c-5aa3fa18433e)

**Comment by naceee** [comment]
I am closing this issue, as the function works and we can discuss the time compexity in the dedicated issue #5
