### ISSUE TITLE
Sampling nondominated points for testing the functions

### ISSUE THREAD

**Issue by naceee** [MilaNedic/moarchiving#4]
Time complexity of functions is usually dependent on the number of points is the archive. Randomly sampling a large set of points might still produce a low number of nondominated points. 

I first (somehow naively) sampled 3D nondominated points like this, which produces nondominated ponts, but the pareto front, probably doesn't represent real world problems:
```python
x = np.random.rand(n_points, 1)
return np.hstack([np.sin(x * np.pi / 2) , np.cos(x * np.pi / 2), x])
```
![newplot(30)](https://github.com/user-attachments/assets/56119336-9ec7-44d3-ab63-d0c7c2d3f450)

I improved the sampling to be done like this and visually it already looks much better, but I'm still not sure if there is some way in which it is usually done? Also the timing results in this case are very different to the previous case, so I guess it is important to pay some attention to it.
```python
x = np.random.rand(n_points, 1)
y = np.random.rand(n_points, 1)
return np.hstack([(1 - np.sin(x * np.pi / 2)) * y, (1 - np.cos(x * np.pi / 2)) * y, np.power(1 - y, 2)])
```
![newplot(33)](https://github.com/user-attachments/assets/20287401-656f-4c6d-8f7b-88a8b538d48e)

**Comment by ttusar** [comment]
You can create linear and spherical approximation sets using the algorithms from [here](https://dis.ijs.si/tea/Publications/Tusar14phd.pdf) (see page 17).

**Comment by naceee** [comment]
I implemented the two algorithms for 3D, now the point clouds look like this.
![newplot(34)](https://github.com/user-attachments/assets/dcb8e9cd-aa7d-4a46-9605-eccdd0a4a1de)

![newplot(35)](https://github.com/user-attachments/assets/dabc30e3-9c21-431e-8ca0-67f3b59b6c7a)

**Comment by ttusar** [comment]
The distributions seem a bit off from what I remember (especially the spherical one), but for the purpose of your tests they should be just fine.

**Comment by naceee** [comment]
Yeah I think the spherical was wrong, this one should be better:
![newplot(36)](https://github.com/user-attachments/assets/a75f07ac-92fb-4fa4-ae7c-6e789057f738)

**Comment by naceee** [comment]
Both algorithms are now implemented in 3D and 4D and used for testing the performance, so I am closing this issue.
