### ISSUE TITLE
naming of factory method

### ISSUE THREAD

**Issue by nikohansen** [MilaNedic/moarchiving#9]
I'd suggest to not use the class naming convention in order to indicate the return value type of the function [GetArchive](https://github.com/MilaNedic/moarchiving/blob/c7516f8944cb5ebba72e31d1390d6ae17fc3b6e9/moarchiving/getarchive.py#L12). I think the usual convention would be something like `get_archive` or `create_archive`.

**Comment by ttusar** [comment]
Yes, that was my mistake, please change it to get_archive.

**Comment by naceee** [comment]
done.
